In [22]:
# Retrieve stock data
import yfinance as yf
import pandas as pd
ticker = "RUB=X"

dataF = yf.download(ticker, start="2023-04-10", end="2023-06-01", interval='15m')
dataF.iloc[:,:]
#dataF.Open.iloc

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Datetime,,,,,,
2023-04-10 03:00:00,80.529999,80.529999,80.529999,80.529999,80.529999,0
2023-04-10 04:00:00,80.529999,80.529999,80.529999,80.529999,80.529999,0
2023-04-10 04:15:00,80.529999,80.529999,80.529999,80.529999,80.529999,0
2023-04-10 04:30:00,80.529999,80.529999,80.529999,80.529999,80.529999,0
2023-04-10 04:45:00,80.529999,80.529999,80.529999,80.529999,80.529999,0
...,...,...,...,...,...,...
2023-05-31 22:45:00,81.553398,81.553398,81.542702,81.542702,81.542702,0
2023-05-31 23:00:00,81.546898,81.546898,81.525002,81.525002,81.525002,0
2023-05-31 23:15:00,81.525002,81.536598,81.525002,81.536598,81.536598,0
2023-05-31 23:30:00,81.538101,81.544998,81.536301,81.544998,81.544998,0
2023-05-31 23:45:00,81.525597,81.540398,81.525597,81.540001,81.540001,0

In [29]:
def signal_generator(df):
    open = df.Open.iloc[-1]
    close = df.Close.iloc[-1]
    previous_open = df.Open.iloc[-2]
    previous_close = df.Close.iloc[-2]
    
    # Bearish Pattern & Selling
    if (open>close and 
    previous_open<previous_close and 
    close<previous_open and
    open>=previous_close):
        return 1

    # Bullish Pattern & Buyying
    elif (open<close and 
        previous_open>previous_close and 
        close>previous_open and
        open<=previous_close):
        return 2
    
    # No clear pattern
    else:
        return 0

signal = []
signal.append(0)
for i in range(1,len(dataF)):
    df = dataF[i-1:i+1]
    signal.append(signal_generator(df))
#signal_generator(data)
dataF["signal"] = signal

In [42]:
dataF.signal.value_counts()
#dataF.iloc[:, :]

signal
0    2391
1      95
2      75
Name: count, dtype: int64

In [39]:
# Buy Price datas
Buy_Price=[]
for signal, buy_price in zip(dataF["signal"], dataF["Open"]):
    if signal == 2:
        Buy_Price.append(buy_price)
# Save Buy_Price to file
with open("stock_data_buy.txt", "w") as file:
    for price in Buy_Price:
        file.write(str(price) + "\n")

In [40]:
Buy_Price

[81.58999633789062,
 82.14749908447266,
 82.08000183105469,
 81.9677963256836,
 80.80000305175781,
 81.4260025024414,
 80.98500061035156,
 81.7603988647461,
 81.75340270996094,
 81.68990325927734,
 81.52899932861328,
 81.810302734375,
 80.9000015258789,
 81.43399810791016,
 81.28099822998047,
 81.26100158691406,
 81.81719970703125,
 81.81379699707031,
 81.3489990234375,
 80.62300109863281,
 80.375,
 81.18199920654297,
 81.39779663085938,
 80.79340362548828,
 81.58599853515625,
 79.7300033569336,
 79.10600280761719,
 79.57569885253906,
 80.11699676513672,
 78.4800033569336,
 79.20320129394531,
 78.07879638671875,
 76.53399658203125,
 77.04109954833984,
 76.82499694824219,
 77.625,
 78.17240142822266,
 77.72039794921875,
 77.13800048828125,
 77.38069915771484,
 77.6729965209961,
 75.48799896240234,
 76.05500030517578,
 76.09049987792969,
 76.10289764404297,
 74.79499816894531,
 75.63899993896484,
 76.631103515625,
 76.9894027709961,
 76.54730224609375,
 77.15139770507812,
 78.7249984741211,
 79.70890045166016,
 79.47000122070312,
 80.48310089111328,
 80.06199645996094,
 80.34500122070312,
 79.66799926757812,
 79.3489990234375,
 79.74299621582031,
 79.86799621582031,
 79.802001953125,
 79.90799713134766,
 79.9229965209961,
 80.05570220947266,
 80.0873031616211,
 80.58000183105469,
 80.04000091552734,
 79.70999908447266,
 79.6520004272461,
 79.89700317382812,
 79.98500061035156,
 79.89099884033203,
 80.83999633789062,
 81.01570129394531]

In [43]:
#Sell Price Datas
Sell_Price=[]
for signal, sell_price in zip(dataF["signal"], dataF["Open"]):
    if signal == 1:
        Sell_Price.append(sell_price)
# Save Buy_Price to file
with open("stock_data_sell.txt", "w") as file:
    for price in Sell_Price:
        file.write(str(price) + "\n")